sudo: false
dist: trusty
language: java

# NB: oraclejdk10 is deprecated
jdk:
   - oraclejdk8
   - openjdk8

matrix:
    allow_failures:
        jdk:
             - oraclejdk11
             - openjdk9
             - openjdk10
             - openjdk11
             - openjdk-ea
